import { Router } from "express";
import authRoutes from "../modules/auth/auth.route";
import dashboardRoutes from "../modules/dashboardManagement/dashboard.route";
import orderRoutes from "../modules/orders/orders.route";
import settingsRoutes from "../modules/settings/settings.route";
import userRoutes from "../modules/users/users.route";
import productRoutes from "../modules/products/products.route";
import reviewRoutes from "../modules/reviews/reviews.route";
import cartRoutes from "../modules/cart/cart.route";
import wishlistRoutes from "../modules/wishlist/wishlist.route";
import checkoutRoutes from "../modules/checkout/checkout.route";
import paymentRoutes from "../modules/payments/payments.route";
import adminCommerceRoutes from "../modules/admin/admin-commerce.route";
import shippingRoutes from "../modules/shipping/shipping.route";
import couponRoutes from "../modules/coupons/coupons.route";
import reportRoutes from "../modules/reports/reports.route";
import categoryRoutes from "../modules/categories/category.route";
import invoiceRoutes, { publicInvoiceRouter } from "../modules/invoices/invoices.route";
import contactRoutes, { adminContactRoutes } from "../modules/contact/contact.route";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/categories", categoryRoutes);
router.use("/products", productRoutes);
router.use("/reviews", reviewRoutes);
router.use("/cart", cartRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/checkout", checkoutRoutes);
router.use("/payments", paymentRoutes);
router.use("/admin", adminCommerceRoutes);
router.use("/shipping", shippingRoutes);
router.use("/coupons", couponRoutes);
router.use("/settings", settingsRoutes);
router.use("/orders", orderRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/public", publicInvoiceRouter);
router.use("/dashboard", dashboardRoutes);
router.use("/dashboard-management", dashboardRoutes);
router.use("/reports", reportRoutes);
router.use("/contact", contactRoutes);
router.use("/admin/contact-messages", adminContactRoutes);

export default router;
